#!/bin/sh

FORBIDDEN_HTTPS_URL="https://github.com/yunojang/husky-prac.git"
FORBIDDEN_SSH_URL="git@github.com:yunojang/husky-prac.git"
FORBIDDEN_REF="refs/heads/master" # insert branch ref

# echo "hello shell" 

remote="$1"
url="$2"

if [ "$remote" != "$FORBIDDEN_HTTPS_URL" -a "$remote" != "$FORBIDDEN_SSH_URL" ]; then
  exit 0
fi

echo "enter_address"

if read local_ref local_sha remote_ref remote_sha
then 
  echo "$remote_ref"
  if [ "$remote_ref" == "$FORBIDDEN_REF" ]
  then 
    echo "DO NOT PUSH it master"
    exit 1 # 에러, push 진행하지 않음
  fi
fi

echo "enter_ref"
exit 0