#!/bin/sh

FORBIDDEN_HTTPS_URL="https://github.com/yunojang/husky-prac.git"
FORBIDDEN_SSH_URL="git@github.com:yunojang/husky-prac.git"
FORBIDDEN_REF="refs/heads/master" # insert branch ref

remote="$1"
url="$2"

if [ "$url" -ne "$FORBIDDEN_HTTPS_URL" -a "$url" -ne "$FORBIDDEN_SSH_URL" ]; then
  # 메인 리포지토리 주소가 아니라, 포크한 리포지토리라면, 허용
  exit 0
fi

if read local_ref local_sha remote_ref remote_sha
then
  if [ "$remote_ref" -eq "$FORBIDDEN_REF" ]; then
    echo "DO NOT PUSH in master"
    exit 1
  fi
fi

exit 0